import axios from "axios";

async function main() {
  const channels = [
    "360",
    "9dcc",
    "AIFilm",
    "Flow",
    "ITAPofmypet",
    "Masks",
    "adp",
    "agust",
    "all",
    "art",
    "automod",
    "ball",
    "base",
    "bookworms",
    "btw",
    "builtdifferent",
    "bycmlab",
    "china",
    "cn-alpha",
    "cnz",
    "consol3",
    "cookies",
    "coop",
    "coop-recs",
    "creatureworld",
    "degen",
    "degen-tools",
    "degendao",
    "degentips",
    "design",
    "design-pieces",
    "dont-do-this",
    "entropybender",
    "ethereum",
    "farc",
    "farcasterroyale",
    "farcasther",
    "farcon",
    "farcon-pics",
    "fashionweb3",
    "fc-ogs",
    "fitness",
    "flying",
    "framedl-pro",
    "frontend",
    "fufu",
    "futurama",
    "glass",
    "guessthechart",
    "habibis",
    "ham",
    "hank",
    "higher",
    "history",
    "houseofdegen",
    "human",
    "johann",
    "jooktuleytoons",
    "karak",
    "lessoninthere",
    "lifeisgood",
    "light",
    "lp",
    "lsd",
    "m3ter-heads",
    "motherlode",
    "nerdery",
    "nook",
    "obscura",
    "ogs",
    "onchainletters",
    "paidgroup",
    "panda",
    "paperboy",
    "perl",
    "powerbadgers",
    "pullup",
    "purpleday",
    "pysop",
    "rainbow",
    "replyguys",
    "robotics",
    "running-jp",
    "salty",
    "school-of-solana",
    "sean",
    "seaport",
    "sofi",
    "space",
    "spirituality",
    "star",
    "staybased",
    "synthesis",
    "tap",
    "the-glyph",
    "theburrow",
    "thecryptomasks",
    "tmp",
    "twocommaclub",
    "unko",
    "valuesdao",
    "vandelay",
    "wake",
    "wearesoearly",
    "wearesosorry",
    "whatisthis",
    "wumblr",
    "yakult1000",
    "yungwknd",
    "yup",
  ].forEach(async (channel) => {
    console.log(`Submitting sweep for ${channel}`);
    await startSweep(channel, 600);
  });
}

async function startSweep(channel: string, limit: number) {
  const formData = new FormData();
  formData.append("channel", channel);
  formData.append("limit", limit.toString());
  formData.append("action", "sweep");

  await axios.post("https://automod.sh/~/admin?_data=routes%2F%7E.admin", formData, {
    headers: {
      "content-type": "multipart/form-data",
      cookie:
        "_session=eyJ1c2VyIjp7ImlkIjoiNTE3OSIsIm5hbWUiOiJqdGdpIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9pLmltZ3VyLmNvbS84QlRrVzBELmpwZyIsImVtYWlsIjpudWxsLCJwbGFuIjoidmlwIiwicGxhbkV4cGlyeSI6bnVsbCwicGxhblRva2VuSWQiOm51bGwsInJvbGUiOiJzdXBlcmFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wMi0yMlQwOTowNTowOC45MzZaIiwidXBkYXRlZEF0IjoiMjAyNC0wMi0yMlQwOTowNTowOC45MzZaIiwiaW52aXRlQ29kZUlkIjpudWxsfSwic3RyYXRlZ3kiOiJmYXJjYXN0ZXIifQ%3D%3D.u8gqLoPJhLib87V%2Bots6kXCdmqfCTgV6DAAKR0hnKoY; ph_phc_xSfqRtKRSoH5A9kPcNkI7J2HNakfQ5KRhFiwVujq8WL_posthog=%7B%22distinct_id%22%3A%225179%22%2C%22%24sesid%22%3A%5B1715217971112%2C%22018f5adf-a2bc-7860-b049-58b7e36967cc%22%2C1715216556732%5D%7D",
    },
  });
}

main();
