/* eslint-disable @typescript-eslint/no-explicit-any */
import { channels } from "./research/channelsnap";

const signers = [564373, 565025, 565060, 565096, 565118, 565180, 565198, 565216, 565235, 565264, 368422];

const disabledChannels = [
  "six",
  "degen",
  "degendao",
  "automod",
  "fitness",
  "replyguys",
  "higher",
  "ogs",
  "light",
  "cnz",
  "samantha",
  "houseofdegen",
  "nook",
  "wearesoearly",
  "lifeisgood",
  "obscura",
  "rainbow",
  "farcasther",
  "design",
  "moments",
  "whydidheleave",
  "unofficial",
  "karak",
  "noob",
  "frontend",
  "minigames",
  "framedl-pro",
  "airdrop",
  "dev",
  "imagine-infra",
  "dont-do-this",
  "farcon",
  "salty",
  "fufu",
  "btw",
  "perl",
  "base",
  "69ism",
  "cheesecoin",
  "airdrop4u",
  "history",
  "space",
  "robotics",
  "Masks",
  "design-pieces",
  "thecryptomasks",
  "lessoninthere",
  "yup",
  "unko",
  "Valuesdao",
  "sonata",
  "bros",
  "panda",
  "the-glyph",
  "builtdifferent",
  "bookworms",
  "art",
  "360",
  "fashion",
  "prohibition",
  "creatureworld",
  "ethereum",
  "spirituality",
  "books",
  "beer",
  "commitment",
  "powermonday",
  "mountains",
  "memes",
  "airstack",
  "superrare",
  "it",
  "powerbadgecabal",
  "farcaster",
  "animeoutcasts",
  "vvbs",
  "geopolitics",
  "lucky",
  "banmal-mode",
  "payflow",
  "crimea",
  "rides",
  "norse-heathenry",
  "tickle",
  "undrgrnd",
  "gaming",
  "Classic",
  "strategy",
  "gm8xx8",
  "quote-art",
  "Venturecapital",
];

const out = [];
for (const c of disabledChannels) {
  const channel = channels.find((ch: any) => ch.id === c.toLowerCase());
  if (channel.moderatorFid) {
    if (signers.includes(channel.moderatorFid)) {
      out.push({
        message: `/${channel.id} should be reenabled`,
        channel: channel.id,
        fid: channel.moderatorFid,
      });
    }
  }
}

console.log(out);
